# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simple_navigation_goals/send.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class send(genpy.Message):
  _md5sum = "a5f0e33b00a5cbe9ea65848687eaa24e"
  _type = "simple_navigation_goals/send"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 time
uint8 age

float64 RXlinear
float64 RYlinear
float64 Rangular
float64 xpose
float64 ypose

float32 zAngle
"""
  __slots__ = ['time','age','RXlinear','RYlinear','Rangular','xpose','ypose','zAngle']
  _slot_types = ['uint32','uint8','float64','float64','float64','float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,age,RXlinear,RYlinear,Rangular,xpose,ypose,zAngle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(send, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0
      if self.age is None:
        self.age = 0
      if self.RXlinear is None:
        self.RXlinear = 0.
      if self.RYlinear is None:
        self.RYlinear = 0.
      if self.Rangular is None:
        self.Rangular = 0.
      if self.xpose is None:
        self.xpose = 0.
      if self.ypose is None:
        self.ypose = 0.
      if self.zAngle is None:
        self.zAngle = 0.
    else:
      self.time = 0
      self.age = 0
      self.RXlinear = 0.
      self.RYlinear = 0.
      self.Rangular = 0.
      self.xpose = 0.
      self.ypose = 0.
      self.zAngle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IB5df().pack(_x.time, _x.age, _x.RXlinear, _x.RYlinear, _x.Rangular, _x.xpose, _x.ypose, _x.zAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.time, _x.age, _x.RXlinear, _x.RYlinear, _x.Rangular, _x.xpose, _x.ypose, _x.zAngle,) = _get_struct_IB5df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IB5df().pack(_x.time, _x.age, _x.RXlinear, _x.RYlinear, _x.Rangular, _x.xpose, _x.ypose, _x.zAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.time, _x.age, _x.RXlinear, _x.RYlinear, _x.Rangular, _x.xpose, _x.ypose, _x.zAngle,) = _get_struct_IB5df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IB5df = None
def _get_struct_IB5df():
    global _struct_IB5df
    if _struct_IB5df is None:
        _struct_IB5df = struct.Struct("<IB5df")
    return _struct_IB5df
