# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from simple_navigation_goals/sensor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sensor(genpy.Message):
  _md5sum = "7b2fc253ad368634d89fd7b84900def5"
  _type = "simple_navigation_goals/sensor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 IR0
int32 IR1
int32 USA
int32 USB
int32 USL
int32 USR
"""
  __slots__ = ['IR0','IR1','USA','USB','USL','USR']
  _slot_types = ['int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       IR0,IR1,USA,USB,USL,USR

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sensor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.IR0 is None:
        self.IR0 = 0
      if self.IR1 is None:
        self.IR1 = 0
      if self.USA is None:
        self.USA = 0
      if self.USB is None:
        self.USB = 0
      if self.USL is None:
        self.USL = 0
      if self.USR is None:
        self.USR = 0
    else:
      self.IR0 = 0
      self.IR1 = 0
      self.USA = 0
      self.USB = 0
      self.USL = 0
      self.USR = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.IR0, _x.IR1, _x.USA, _x.USB, _x.USL, _x.USR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.IR0, _x.IR1, _x.USA, _x.USB, _x.USL, _x.USR,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.IR0, _x.IR1, _x.USA, _x.USB, _x.USL, _x.USR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.IR0, _x.IR1, _x.USA, _x.USB, _x.USL, _x.USR,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
